export {
  COMMISSION_TYPE,
  COMMISSION_POSITIONING_BUTTONS,
  COMMISSION_CONFIG,
  MIN_TEXT_LENGTH,
  MAX_COMMISSION_RETRY_COUNT,
  POSITION_COORDINATES,
  COMMISSION_STATUS_REGIONS,
  THRESHOLDS,
  PATHS,
  OCR_REGIONS,
} from "./game-constants.js";
