/** 文件路径常量 */
export const PATHS = {
  SUPPORT_LIST: "name.json",
  OUTPUT_DIR: "Data",
  FIGHT_SCRIPT_BASE: "assets",
  TALK_PROCESS_BASE: "assets/process",
  COMMISSIONS_DATA: "Data/commissions_data.json",
  COMPLETED_IMAGE: "Data/RecognitionObject/Completed.png",
  UNCOMPLETED_IMAGE: "Data/RecognitionObject/UnCompleted.png",
  TALK_EXIT_IMAGE: "Data/RecognitionObject/TalkExit.png",
  TALK_ICON_IMAGE: "Data/RecognitionObject/TalkIcon.png",
  F_ICON_IMAGE: "Data/RecognitionObject/F.png",
  PAIMON_MENU_IMAGE: "Data/RecognitionObject/paimon_menu.png",
  TEAM_IMAGE: "Data/RecognitionObject/team.png",
  STORE_IMAGE: "Data/RecognitionObject/商店.png",
  REPLACE_IMAGE: "Data/RecognitionObject/更换.png",
  JOIN_IMAGE: "Data/RecognitionObject/加入.png",
  TEAM_CONFIG_IMAGE: "Data/RecognitionObject/队伍配置.png",
  DISABLED_UI_IMAGE: "Data/RecognitionObject/disabled_ui.png",
  ICON_BIGMAP_COMMISSION: "Data/RecognitionObject/IconBigmapCommission.jpg",
  ICON_QUESTION_COMMISSION: "Data/RecognitionObject/IconQuestionCommission.png",
  ICON_TASK_COMMISSION: "Data/RecognitionObject/IconTaskCommission.png",
  CHARACTER_IMAGE_DIR: "Data/characterimage/",
  AVATAR_DATA: "Data/avatar/combat_avatar.json",
};
